cors:
  originPatterns: http://localhost:3000,http://localhost:4200,http://localhost:8080
spring:
  mvc:
    locale: pt_BR
    locale-resolver: fixed
  datasource:
    url: jdbc:mysql://localhost:3306/egs19502fp.db?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: false
  messages:
    encoding: UTF-8
    basename: messages_pt_BR
server:
  port: 8080
  servlet:
    context-path: /api