CREATE TABLE IF NOT EXISTS payroll (
    id_payroll INT NOT NULL AUTO_INCREMENT,
    company_id INT NOT NULL DEFAULT 1,
    employee_id INT NOT NULL,
    month ENUM(
        'JANUARY',
        'FEBRUARY',
        'MARCH',
        'APRIL',
        'MAY',
        'JUNE',
        'JULY',
        'AUGUST',
        'SEPTEMBER',
        'OCTOBER',
        'NOVEMBER',
        'DECEMBER') NOT NULL,
    year INT NOT NULL,
    gross_salary DECIMAL(10, 2) NOT NULL,
    inss_base_amount DECIMAL(10, 2) NOT NULL,
    inss_tax_rate DECIMAL(5, 2) NOT NULL,
    irrf_base_amout DECIMAL(10, 2) NOT NULL,
    irrf_tax_rate DECIMAL(5, 2) NOT NULL,
    fgts_base_amout DECIMAL(10, 2) NOT NULL,
    fgts_payed DECIMAL(10, 2) NOT NULL,
    total_additions DECIMAL(10, 2) NOT NULL,
    total_discounts DECIMAL(10, 2) NOT NULL,
    total_liquid DECIMAL(10, 2) NOT NULL,
    status ENUM(
        'PENDING',
        'RELEASED',
        'APPROVED',
        'DENIED',
        'PAID',
        'CANCELED') NOT NULL DEFAULT 'PENDING',
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id_payroll),
    FOREIGN KEY (company_id) REFERENCES company(id_company),
    FOREIGN KEY (employee_id) REFERENCES employee(id_employee)
);