CREATE TABLE IF NOT EXISTS tax_or_value (
    id_tax_or_value INT NOT NULL AUTO_INCREMENT,
    type ENUM('MINIMUM_WAGE', 'DAYCARE_ALLOWANCE', 'TRANSPORT_ALLOWANCE', 'MEAL_ALLOWANCE', 'SALES_ALLOWANCE',
              'NIGHT_SHIFT_ALLOWANCE', 'UNHEALTHINESS_ALLOWANCE', 'DANGEROUSNESS_ALLOWANCE', 'FAMILY_ALLOWANCE',
              'TIME_SERVICE_ALLOWANCE', 'INSS', 'IRRF', 'FGTS', 'TRANSPORT_DISCOUNT', 'MEAL_DISCOUNT') NOT NULL,
    name VARCHAR(40) NOT NULL,
    tax_percentage DECIMAL(5, 2) NOT NULL,
    minimum_wage DECIMAL(10, 2) NOT NULL,
    maximum_wage DECIMAL(10, 2) NOT NULL,
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id_tax_or_value)
);