CREATE TABLE IF NOT EXISTS tax_or_value (
    id_tax_or_value INT NOT NULL AUTO_INCREMENT,
    type ENUM('MINIMUM_WAGE', 'DAYCARE_ALLOWANCE', 'TRANSPORT_ALLOWANCE', 'MEAL_ALLOWANCE', 'SALES_ALLOWANCE',
              'NIGHT_SHIFT_ALLOWANCE', 'UNHEALTHINESS_ALLOWANCE', 'DANGEROUSNESS_ALLOWANCE', 'FAMILY_ALLOWANCE',
              'TIME_SERVICE_ALLOWANCE', 'INSS', 'IRRF', 'FGTS', 'TRANSPORT_DISCOUNT', 'MEAL_DISCOUNT') NOT NULL,
    range_id INT,
    range_minimum_wage DECIMAL(10, 2),
    range_maximum_wage DECIMAL(10, 2),
    fixed_value DECIMAL(10, 2),
    tax_percentage DECIMAL(5, 2),
    description VARCHAR(160) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id_tax_or_value)
);