CREATE TABLE IF NOT EXISTS rubric (
    id_rubric INT NOT NULL AUTO_INCREMENT,
    description VARCHAR(120) NOT NULL,
    type TINYINT(1) NOT NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id_rubric)
);