-- Generated by: https://www.4devs.com.br/gerador_de_pessoas

INSERT INTO employee_dependent
    (employee_id, name, rg, cpf, birth_date, gender, special_needs)
VALUES
    -- Salário Família
    (8, 'Miguel Lucas Novaes', '385644565', '12460465980', '2015-08-27', 'MALE', 1),
    (23, 'Aurora Mariana Brito', '206972763', '59772050668', '2013-04-05', 'FEMALE', 1),
    (30, 'Fábio Evandro Nascimento', '119176464', '21475242042', '2018-09-15', 'MALE', 0),
    (45, 'Luan Theo Castro', '147928308', '46710458008', '2020-08-01', 'MALE', 0),

    -- Auxílio Creche
    (47, 'Maitê Letícia Araújo', '248124250', '89297933718', '2024-02-10', 'FEMALE', 0),
    (51, 'Thales Michel Rocha', '339736367', '43157756656', '2023-12-18', 'MALE', 0);