-- Generated by: https://www.4devs.com.br/gerador_de_pessoas

INSERT INTO user
    (name, email, password)
VALUES
    ('Administrador', 'admin@domain.com', '7fcf4ba391c48784edde599889d6e3f1e47a27db36ecc050cc92f259bfac38afad2c68a1ae804d77075e8fb722503f3eca2b2c1006ee6f6c7b7628cb45fffd1d'),

    -- Administrativo
    ('Hugo Osvaldo Pereira', 'hugo_osvaldo_pereira@domain.com', '79dec184f715c19b147b50df57c1b18aa0558ecb13bc4b3ca25e8413f45a1f4a7a4dfecedef15226fdda5086dea5b9ffe34e6be361a28214cc61d735a1f99c15'),
    ('Renata Carolina Moreira', 'renata_carolina_moreira@domain.com', 'c56cbab8a261d4706f93f3706922d0136773952528a26ba279024b7a378effde079b518db3ddad4f609f43379a62c9d930caca04eccc05715d6e39dd5101a3d0'),

    -- Financeiro
    ('Sandra Rita Corte Real', 'sandra_rita_corte_real@domain.com', '2d9a79f8efe47c2ebc26ee9903f32cd91192dd441107829562087b9c4585ec0e3434ab7b1c16352900bee720dc912700227e71bf078736c3e915d9c32e376a75'),
    ('Renato Diego Thales Lopes', 'renato_diego_thales_lopes@domain.com', '19c240ea399215ba6ee605acd3441d7fb2e509cb660e7c430216da2766ad066088b3c598b7ff30cf2cd4f54b1e4ce28e5c8fa629c79dc8708eee3ec20daec49e'),

    -- Recursos Humanos
    ('Larissa Andreia Vieira', 'larissa_andreia_vieira@domain.com', 'bbd69d6f4504c52b7ff6f3214c26493da60e0a6b3513df8a814ee98212a90d392b0aa5ea64a4bee5b9b20405133927713d0d8e60acf5f72412a858842ddffdab'),

    -- Outros Gestores
    ('Benício Victor Ferreira', 'benício_victor_ferreira@domain.com', 'b083155d9949c3ee72b6858e2e18bda82367431634f2ea6dd7455d811dba584bd481772d43402dbe90216fc53a4adef970e436e542a68135f0cfb7c99d8b1538'),
    ('Pietro Jorge Barros', 'pietro_jorge_barros@domain.com', '0fa0d5d6fbde4c62146806752ef1be05e6a4736f6d1b221eab1595bc1c5898cfd9b67b2898b95b99d1ac5310c65732d8ee1be93432e779a31ef030648c61edb3'),
    ('Giovane Araújo', 'giovane_araujo@domain.com', 'a9b79bd4e2944a9dc70af036de6630c2f5592262992cadcee293baad85fbe4091d9dd0fd02179bfba89c3dba07423c32131f7a378a95c15ed2a5b84f7e9c0810');