-- Generated by: https://www.4devs.com.br/gerador_de_pessoas

INSERT INTO employee
    (name, rg, cpf, birth_date, gender, address_street, address_number, address_neighborhood, address_city, address_uf, address_zip_code, phone, email, admission_date, time_service_allowance, department_id, job_id, work_shift_id, salary)
VALUES
    -- Administrativo
    ('Hugo Osvaldo Pereira', '223294482', '90571964419', '1987-05-03', 'MALE', 'Rua Antônio Camilo dos Nascimento Junior', '762', 'Memorare', 'Cascavel', 'PR', '85780000', '91983213016', 'hugo_osvaldo_pereira@domain.com', '2014-01-01', 1, 1, 7, 2, 9000.00), -- CEO
    ('Renata Carolina Moreira', '377424067', '44619937525', '1997-02-17', 'FEMALE', 'Conjunto Asteka', '780', 'São José', 'Cascavel', 'PR', '85780000', '82992208073', 'renata_carolina_moreira@domain.com', '2015-03-01', 0, 1, 5, 2, 6000.00),                  -- Assistente Administrativo Senior
    ('Mateus Gabriel Rodrigues', '103725404', '05383894608', '1992-01-14', 'MALE', 'Rua Jonas Sepúlveda Lima', '949', 'Caratinga', 'Cascavel', 'PR', '85780000', '86983335967', 'mateus_gabriel_rodrigues@domain.com', '2023-12-01', 0, 1, 1, 6, 1100.00),        -- Estagiário

    -- Financeiro
    ('Sandra Rita Corte Real', '495872167', '52966694106', '1991-03-14', 'FEMALE', 'Rua Pioneira Ângela Bulla Calvi', '584', 'Jardim Paulista III', 'Cascavel', 'PR', '85780000', '96988396560', 'sandra_rita_corte_real@domain.com', '2015-03-01', 0, 2, 17, 2, 8400.00), -- CFO
    ('Renato Diego Thales Lopes', '217041000', '85684485421', '1986-10-02', 'MALE', 'Rua B', '320', 'São Geraldo', 'Cascavel', 'PR', '85780000', '69984315714', 'renato_diego_thales_lopes@domain.com', '2015-01-01', 0, 2, 15, 2, 6000.00),                               -- Contador Senior
    ('Felipe Cauã Ferreira', '123781450', '17959059993', '1975-02-03', 'MALE', 'Travessa Gouveia Nóbrega', '175', 'São Rogério', 'Cascavel', 'PR', '85780000', '81986960878', 'felipe_caua_ferreira@domain.com', '2018-07-01', 0, 2, 11, 2, 3400.00),                      -- Analista Financeiro Mid Level

    -- Recursos Humanos
    ('Larissa Andreia Vieira', '303353958', '71333385480', '1982-02-06', 'FEMALE', 'Rua América do Sul', '702', 'Nova Boa Vista', 'Cascavel', 'PR', '85780000', '73991949620', 'larissa_andreia_vieira@domain.com', '2015-08-10', 0, 3, 24, 2, 7300.00), -- CHFO
    ('Jennifer Stefany Novaes', '407724400', '99794204994', '1989-02-08', 'FEMALE', 'Rua São Paulo', '785', 'Parque Soledade', 'Cascavel', 'PR', '85780000', '91984010352', 'jennifer_stefany_novaes@domain.com', '2019-05-01', 0, 3, 20, 2, 2900.00),   -- Assistente de RH Junior
    ('Elisa Adriana Oliveira', '472981845', '69598972038', '1990-08-01', 'FEMALE', 'Rua Rondônia', '826', 'Monte Carlo', 'Cascavel', 'PR', '85780000', '92993278545', 'elisa_adriana_oliveira@domain.com', '2021-08-01', 0, 3, 20, 2, 2500.00),          -- Assistente de RH Junior

    -- Pesquisa e Desenvolvimento
    ('Benício Victor Ferreira', '409240813', '62904942106', '1986-12-17', 'MALE', 'Rua América do Sul', '702', 'Nova Boa Vista', 'Cascavel', 'PR', '85780000', '28986861860', 'benício_victor_ferreira@domain.com', '2016-06-01', 0, 4, 37, 2, 7000.00),                          -- CTO
    ('Rafaela Jennifer Aparício', '176203722', '80312205570', '1988-07-02', 'FEMALE', 'Avenida Contorno Norte', '724', 'Conjunto Habitacional Requião', 'Cascavel', 'PR', '85780000', '63994919892', 'rafaela_jennifer_aparicio@domain.com', '2017-08-01', 0, 4, 32, 2, 4700.00), -- DBA Senior
    ('Nina Kamilly Brito', '114472634', '44756603351', '1995-11-02', 'FEMALE', 'Rua Carlos Marighella', '337', 'Cascata', 'Cascavel', 'PR', '85780000', '95985759327', 'nina_kamilly_brito@domain.com', '2017-04-20', 0, 4, 35, 2, 4600.00),                                      -- Arquiteto Senior
    ('Francisco Corte Real', '378747204', '06445213332', '1996-03-24', 'MALE', 'Rua Aluísio Lobo', '313', 'São Francisco', 'Cascavel', 'PR', '85780000', '79991521929', 'francisco_corte_real@domain.com', '2019-11-01', 0, 4, 29, 2, 3900.00),                                   -- Eng. Software Senior

    -- Infraestrutura de TI
    ('Henry Hugo Lima', '369254326', '05375596636', '1990-07-06', 'MALE', 'Rua Capitão José Otto Sampaio', '881', 'Glória', 'Cascavel', 'PR', '85780000', '31992829303', 'henry_hugo_lima@domain.com', '2018-07-01', 0, 5, 42, 2, 3900.00),          -- Analista de Redes
    ('Jorge Kevin Rodrigues', '341024028', '07252580474', '2004-03-21', 'MALE', 'Rua Natan Alves de Brito', '413', 'Alvorada', 'Cascavel', 'PR', '85780000', '61981456486', 'jorge_kevin_rodrigues@domain.com', '2024-01-20', 0, 5, 38, 5, 1100.00), -- Estagiário

    -- Marketing
    ('Pietro Jorge Barros', '121145554', '80154450600', '1973-08-15', 'MALE', 'Quadra QN 22 Conjunto 5', '470', 'Riacho Fundo II', 'Cascavel', 'PR', '85780000', '62988173735', 'pietro_jorge_barros@domain.com', '2014-01-01', 1, 6, 50, 2, 6800.00),   -- CMO
    ('Theo Victor Manoel Ribeiro', '371515130', '70921520468', '1985-10-18', 'MALE', 'Rua Coletora 2', '238', 'Vila Vitória', 'Cascavel', 'PR', '85780000', '54989253995', 'theo_victor_manoel_ribeiro@domain.com', '2019-05-01', 0, 6, 47, 2, 3400.00), -- Analista de Marketing Mid Level
    ('Hadassa Letícia da Costa', '30746542283', '30746542283', '1987-03-23', 'FEMALE', 'Rua Manoel Aninha', '116', 'Pescaria', 'Cascavel', 'PR', '85780000', '54989253995', 'hadasssa_leticia_costa@domain.com', '2020-09-10', 0, 6, 47, 2, 3100.00), -- Analista de Marketing Mid Level

    -- Vendas
    ('Vera Eliane Lopes', '168622592', '97172829190', '1981-07-15', 'FEMALE', 'Travessa Filó', '302', 'Felipe Camarão', 'Cascavel', 'PR', '85780000', '37982663172', 'vera_eliane_lopes@domain.com', '2014-01-01', 1, 7, 56, 2, 5900.00),
    ('Letícia Brenda Brito', '179258187', '29740613705', '1998-02-03', 'FEMALE', 'Rua Saadeddine Ali Wardeni', '112', 'Jardim Guaporé', 'Cascavel', 'PR', '85780000', '96989873810', 'letícia_brenda_brito@domain.com', '2018-06-15', 0, 7, 55, 2, 5100.00),
    ('Lorena Carolina Novaes', '207557512', '89777224974', '1993-08-22', 'FEMALE', 'Travessa Juvenal Lúcio', '934', 'Belo Horizonte', 'Cascavel', 'PR', '85780000', '61995336014', 'lorena_carolina_novaes@domain.com', '2018-06-15', 0, 7, 53, 2, 3400.00),
    ('Mateus Lorenzo Gonçalves', '504464188', '86400678646', '1989-08-03', 'MALE', 'Rua Antônio Sanches Moreno', '459', 'Conceição', 'Cascavel', 'PR', '85780000', '83985291308', 'mateus_lorenzo_goncalves@domain.com', '2022-02-01', 0, 7, 53, 2, 2800.00),

    -- Atendimento ao Cliente (SAC)
    ('Nathan José Peixoto', '416243319', '41261825942', '1983-08-17', 'MALE', 'Rua Domingos Almeida', '506', 'João de Deus', 'Cascavel', 'PR', '85780000', '69996561080', 'nathan_jose_peixoto@domain.com', '2016-01-01', 0, 8, 61, 2, 3400.00),
    ('Felipe Tomás Ribeiro', '431085341', '54900631140', '1987-09-04', 'MALE', 'Rua Zéca Serra', '838', 'Universitário', 'Cascavel', 'PR', '85780000', '63996639462', 'felipe_tomas_ribeiro@domain.com', '2018-07-01', 0, 8, 59, 2, 2600.00),
    ('Carlos Antonio Brito', '217934316', '46503042450', '1995-12-03', 'MALE', 'Rua Manoel Lelé', '393', 'Ponta Negra', 'Cascavel', 'PR', '85780000', '27981045548', 'carlos_antonio_brito@domain.com', '2023-08-01', 0, 8, 57, 5, 1100.00),
    ('Betina Vera Santos', '385894478', '92443302881', '1994-06-11', 'FEMALE', 'Beco Internacional', '112', 'Mauazinho', 'Cascavel', 'PR', '85780000', '47986944826', 'betina_vera_santos@domain.com', '2022-10-10', 0, 8, 57, 7, 1100.00),

    -- Produção
    ('Giovane Araújo', '315184206', '35410838408', '1982-03-10', 'MALE', 'Avenida São Bartolomeu', '472', 'Setor Major Carlos', 'Cascavel', 'PR', '85780000', '85997557960', 'giovane_araujo@domain.com', '2014-01-01', 1, 9, 78, 2, 6100.00), -- COO

        -- Período 1
    ('Bryan Filipe Jesus', '229887375', '72077490900', '1986-04-16', 'MALE', 'Rua Flor de Minas', '703', 'Liberdade', 'Cascavel', 'PR', '85780000', '95983173503', 'bryan_filipe_jesus@domain.com', '2017-05-01', 0, 9, 76, 1, 4700.00),                               -- Supervisor
    ('Pedro Silvio Carvalho', '396264827', '11736049364', '1988-11-03', 'MALE', 'Rua Safira', '108', 'Balneário Arco-Íris', 'Cascavel', 'PR', '85780000', '83988865521', 'pedro_silvio_carvalho@domain.com', '2020-07-10', 0, 9, 73, 1, 3800.00),                      -- Técnico
    ('Lavínia Alana Mendes', '384443394', '12705088571', '1992-09-22', 'FEMALE', 'Rua Lúcio Mendonça', '390', 'Indianópolis', 'Cascavel', 'PR', '85780000', '89981796193', 'lavinia_alana_mendes@domain.com', '2023-04-01', 0, 9, 70, 1, 3250.00),                     -- Operador
    ('Clarice Mariane Lima', '381723197', '26676436744', '1997-06-04', 'FEMALE', 'Rua Manoel de Severino', '667', 'Fragoso', 'Cascavel', 'PR', '85780000', '84983010564', 'clarice_mariane_lima@domain.com', '2023-07-10', 0, 9, 69, 1, 2850.00),                      -- Operador
    ('Simone Carla Nascimento', '231096860', '67404362156', '1987-01-13', 'FEMALE', 'Rua Paraíso do Tanque', '600', 'Dom Jaime Câmara', 'Cascavel', 'PR', '85780000', '231096860', 'simone_carla_nascimento@domain.com', '2019-09-01', 0, 9, 67, 1, 3250.00),          -- Produção
    ('Emanuelly Claudia Duarte', '172223568', '94539910230', '1993-03-18', 'FEMALE', 'Rua Airton Medeiros Felipe', '907', 'Dom Jaime Câmara', 'Cascavel', 'PR', '85780000', '71999235129', 'emanuelly_claudia_duarte@domain.com', '2023-09-01', 0, 9, 66, 1, 2400.00), -- Produção

        -- Período 2
    ('Marcela Cecília Monteiro', '247450686', '23779703629', '1989-01-17', 'FEMALE', 'Rua Antônio do BA', '637', 'Centro', 'Cascavel', 'PR', '85780000', '95983173503', 'marcela_cecilia_monteiro@domain.com', '2018-07-10', 0, 9, 75, 2, 4100.00),             -- Supervisor
    ('Cassio Raimundo de Paula', '403651785', '13653006333', '1988-11-03', 'MALE', 'Travessa Brasil', '515', 'Santa Rosa', 'Cascavel', 'PR', '85780000', '67999992307', 'cassio_raimundo_paula@domain.com', '2020-02-10', 0, 9, 73, 2, 3900.00),                -- Técnico
    ('Ruan Yuri Julio Pires', '195003500', '94016488320', '1992-05-23', 'MALE', 'Quadra SRES Quadra 10 Bloco E', '572', 'Cruzeiro Velho', 'Cascavel', 'PR', '85780000', '27985342006', 'ruan_yuri_julio_pires@domain.com', '2019-12-01', 0, 9, 69, 2, 3125.00), -- Operador
    ('Luiza Allana da Silva', '339234003', '25884991983', '1983-01-28', 'FEMALE', 'Avenida Aviador Irapuan Rocha', '689', 'Dona Fátima', 'Cascavel', 'PR', '85780000', '91994366998', 'luiza_allana_silva@domain.com', '2017-07-10', 0, 9, 70, 2, 3650.00),     -- Operador
    ('Isaac Samuel da Paz', '122097713', '56397035808', '1993-07-26', 'MALE', 'Rua Real Grandeza', '662', 'Dona Aurora', 'Cascavel', 'PR', '85780000', '86998095001', 'isaac_samuel_paz@domain.com', '2021-06-15', 0, 9, 66, 2, 2750.00),                       -- Produção
    ('Josefa Nicole Carvalho', '103754325', '54599144770', '2001-11-21', 'FEMALE', 'Quadra EQNP 11/15 Bloco C', '457', 'Ceilândia', 'Cascavel', 'PR', '85780000', '67986840265', 'josefa_nicole_carvalho@domain.com', '2018-07-01', 0, 9, 66, 2, 3100.00),      -- Produção

        -- Perídoo 3
    ('Laís Renata da Cruz', '441189660', '95545973044', '1987-05-03', 'FEMALE', 'Rua Duque de Caxias', '332', 'São Cristovam', 'Cascavel', 'PR', '85780000', '73984446593', 'lais_renata_cruz@domain.com', '2018-09-01', 0, 9, 76, 3, 4500.00),                            -- Supervisor
    ('Levi Freitas', '471456275', '51466534290', '1982-09-15', 'MALE', 'Rua Maria Lúcia da Fonseca Matos', '813', 'São Paulo', 'Cascavel', 'PR', '85780000', '68998705109', 'levi_freitas@domain.com', '2022-04-10', 0, 9, 72, 3, 3150.00),                                -- Técnico
    ('Gabriela Luna Monteiro', '148147604', '35677318230', '1990-04-20', 'FEMALE', '3ª Vila Sacramento Pio', '967', 'Pero Vaz', 'Cascavel', 'PR', '85780000', '86996958701', 'gabriela_luna_monteiro@domain.com', '2019-08-01', 0, 9, 70, 3, 3600.00),                     -- Operador
    ('Iago Paulo da Conceição', '494083347', '12638075345', '1982-08-10', 'MALE', 'Rua Cícero Antônio de Sousa', '337', 'Jardim Novo Campos Elíseos', 'Cascavel', 'PR', '85780000', '92985422060', 'iago_paulo_conceicao@domain.com', '2020-03-10', 0, 9, 70, 3, 3450.00), -- Operador
    ('Carlos Eduardo Aragão', '490251961', '21678735221', '1985-03-12', 'MALE', 'Travessa das Carnaúbas', '512', 'Sabiá', 'Cascavel', 'PR', '85780000', '84991069141', 'carlos_eduardo_aragao@domain.com', '2022-07-01', 0, 9, 65, 3, 1950.00),                            -- Produção
    ('Daiane Marli Castro', '170204364', '67484656305', '1984-09-08', 'FEMALE', 'Caminho 14', '247', 'Mussurunga II', 'Cascavel', 'PR', '85780000', '62994196357', 'diane_marli_castro@domain.com', '2021-03-14', 0, 9, 37, 3, 3150.00),                                   -- Produção

        -- Período 4
    ('Hugo Samuel Silva', '133562141', '53132358851', '1991-08-13', 'MALE', 'Rua José Bonifácio', '549', 'Novo Umuarama', 'Cascavel', 'PR', '85780000', '83986471631', 'hugo_samuel_silva@domain.com', '2014-02-01', 1, 9, 76, 4, 4200.00),          -- Supervisor
    ('Cesar Murilo Castro', '377821299', '63375893272', '1989-11-18', 'MALE', 'Rua Mário Brígido', '189', 'Lote Seis', 'Cascavel', 'PR', '85780000', '68998705109', 'cesar_murilo_castro@domain.com', '2023-05-01', 0, 9, 72, 4, 2800.00),           -- Técnico
    ('Elias Luan Araújo', '409598926', '63239136660', '1996-10-15', 'MALE', 'Rua Antonio Amâncio da Silva', '409', 'DNER', 'Cascavel', 'PR', '85780000', '47984629055', 'elias_luan_araujo@domain.com', '2021-08-10', 0, 9, 69, 4, 2900.00),         -- Operador
    ('Luiza Alana Araújo', '164703603', '45281096702', '1998-06-26', 'FEMALE', 'Loteamento Jardim Pituaçu', '697', 'Boca do Rio', 'Cascavel', 'PR', '85780000', '65983744338', 'luiza_alana_araujo@domain.com', '2021-08-10', 0, 9, 69, 4, 2900.00), -- Operador
    ('Vitor Rodrigo Campos', '199772010', '76306757805', '1991-07-08', 'MALE', 'Rua Júpiter', '174', 'Igapó', 'Cascavel', 'PR', '85780000', '54983440677', 'vitor_rodrigo_campos@domain.com', '2020-04-10', 0, 9, 65, 4, 2200.00),                   -- Produção
    ('Luís Nathan Barbosa', '447402705', '29902327966', '1982-11-23', 'MALE', 'Rua GB 9', '679', 'Guanabara II', 'Cascavel', 'PR', '85780000', '67997678892', 'luis_nathan_barbosa@domain.com', '2018-08-01', 0, 9, 67, 4, 3300.00),                 -- Produção

    -- Qualidade
    ('Joaquim da Conceição', '265786381', '83136583981', '1992-05-28', 'MALE', 'Rua Cora Coralina', '759', 'Japiim', 'Cascavel', 'PR', '85780000', '69986093481', 'joaquim_conceicao@domain.com', '2019-05-20', 0, 10, 86, 2, 3900.00),
    ('Bianca Giovana Rocha', '464169562', '32029638560', '1994-03-11', 'FEMALE', 'Rua Anália Gomes Merhy', '811', 'Thomaz Coelho', 'Cascavel', 'PR', '85780000', '27995981100', 'bianca_giovana_rocha@domain.com', '2020-08-01', 0, 10, 81, 2, 2350.00),
    ('Isabel Luciana Nunes', '447429978', '38855632400', '1999-12-04', 'FEMALE', 'Vila Alegria do Castro Neves', '165', 'Mata Atlântica', 'Cascavel', 'PR', '85780000', '84998881690', 'isabel_luciana_nunes@domain.com', '2023-07-01', 0, 10, 79, 5, 1100.00),
    ('Julia Antônia Fogaça', '262262320', '31904134602', '1997-10-05', 'FEMALE', 'Rua Clemente Pereira', '590', 'Garcia', 'Cascavel', 'PR', '85780000', '47981657793', 'julia_antonia_fogaca@domain.com', '2023-05-10', 0, 10, 79, 6, 1100.00),

    -- Jurídico
    ('Tiago Julio Campos', '356110291', '58551867253', '1994-06-08', 'MALE', 'Travessa Um', '177', 'Paraíso', 'Cascavel', 'PR', '85780000', '85983197686', 'tiago_julio_campos@domain.com', '2017-05-15', 0, 11, 86, 6, 4700.00),
    ('Karine Antônia de Paula', '229665780', '96240733768', '2000-07-18', 'FEMALE', 'Rua Maria Cantilde Gomes', '204', 'Petrolândia', 'Cascavel', 'PR', '85780000', '96995799901', 'karine_antonia_paula@domain.com', '2021-06-01', 0, 11, 85, 6, 3500.00),

    -- Limpeza
    ('Raimunda Sales', '110914661', '42704761760', '1982-05-21', 'FEMALE', 'Quadra Quadra 38', '507', 'Núcleo Residencial Brasília', 'Cascavel', 'PR', '85780000', '27983770296', 'raimunda_sales@domain.com', '2016-03-10', 0, 12, 91, 2, 2900.00),
    ('Carla Eduarda Rodrigues', '340748229', '53785524943', '1988-07-16', 'FEMALE', 'Rua N-007', '270', 'Setor Novo Horizonte', 'Cascavel', 'PR', '85780000', '83981693311', 'carla_eduarda_rodrigues@domain.com', '2018-06-01', 0, 12, 91, 3, 2900.00),
    ('Rebeca Luzia Rezende', '497072257', '39987173152', '1991-12-12', 'FEMALE', 'Rua Cláudio Lúcio Monteiro', '815', 'Remendos', 'Cascavel', 'PR', '85780000', '96989006876', 'rebeca_luzia_rezende@domain.com', '2020-05-10', 0, 12, 91, 3, 2900.00);