-- https://www.gov.br/esocial/pt-br/documentacao-tecnica/manuais/leiautes-esocial-nt-05-2022-html/tabelas.html#03

INSERT INTO rubric
    (code, name, kind, description, type)
VALUES
    -- Proventos: Códigos 1000 à 5999
    (1000, "Horas Normais", "Salário, vencimento, soldo", "Corresponde ao salário básico contratual do empregado contratado de acordo com a CLT e o vencimento mensal do servidor público e do militar", "INCOME"),
    (1001, "Subsídio", "Subsídio", "Corresponde à remuneração paga na forma de subsídio", "INCOME"),
    (1002, "DSR", "Descanso semanal remunerado - DSR", "Valor correspondente a um dia de trabalho incidente sobre as verbas de natureza variável, tais como: horas extras, adicional noturno, produção, comissão, etc.", "INCOME"),
    (1003, "Hora Extra", "Horas extraordinárias", "Valor correspondente à hora extraordinária de trabalho, acrescido de percentual de no mínimo 50%", "INCOME"),
    (1009, "Salário Família - Complemento", "Salário-família - Complemento", "Valor excedente ao do fixado pela previdência social para o salário-família", "INCOME"),
    (1011, "Sobreaviso", "Sobreaviso e prontidão", "Valor correspondente a um percentual da hora normal de trabalho", "INCOME"),
    (1020, "Férias", "Férias", "Valor correspondente à remuneração a que faz jus na época da concessão das férias e o adicional constitucional a que o trabalhador adquiriu direito, inclusive o adiantamento de férias, quando pagas antecipadamente – nessa opção deve ser classificado também o valor pago mensalmente ao trabalhador avulso e ao empregado com contrato de trabalho intermitente, a título de férias", "INCOME"),
    (1021, "Férias - Gratificação superior 20 Dias", "Férias - Abono ou gratificação de férias superior a 20 dias", "Remuneração a título de abono de férias, desde que excedente a 20 (vinte) dias do salário e concedido em virtude de cláusula contratual, do regulamento da empresa, de convenção ou acordo coletivo, como por exemplo, o art. 144 da CLT", "INCOME"),
    (1022, "Férias - Gratificação não excedente 20 Dias", "Férias - Abono ou gratificação de férias não excedente a 20 dias", "Remuneração a título de abono de férias, desde que não excedente a 20 (vinte) dias do salário e concedido em virtude de cláusula contratual, do regulamento da empresa, de convenção ou acordo coletivo, como por exemplo o art. 144 da CLT", "INCOME"),
    (1023, "Férias - Abono Pecuniário", "Férias - Abono pecuniário", "Valor correspondente a conversão em dinheiro de parte dos dias de férias a que o trabalhador adquiriu direito, inclusive o adicional constitucional", "INCOME"),
    (1040, "Licença-Prêmio", "Licença-prêmio", "Valor relativo a licença-prêmio, em decorrência de afastamento do trabalho", "INCOME"),
    (1041, "Licença-Prêmio Indenizada", "Licença-prêmio indenizada", "Remuneração de dias nos quais o trabalhador esteja afastado do trabalho sem prejuízo de sua remuneração", "INCOME"),
    (1099, "Outras Verbas Salariais", "Outras verbas salariais", "Outras verbas salariais não previstas nos demais itens", "INCOME"),
    (1201, "Cargo Confiança", "Adicional de função / cargo confiança", "Adicional ou gratificação concedida em virtude de cargo ou função de confiança", "INCOME"),
    (1202, "Adicional Insalubridade", "Adicional de insalubridade", "Adicional por serviços em condições de insalubridade", "INCOME"),
    (1203, "Adicional Periculosidade", "Adicional de periculosidade", "Adicional por serviços em condições perigosas", "INCOME"),
    (1204, "Adicional Transferência", "Adicional de transferência", "Adicional em razão de transferência de trabalhador, enquanto durar a transferência", "INCOME"),
    (1205, "Adicional Noturno", "Adicional noturno", "Adicional por trabalho em horário noturno", "INCOME"),
    (1206, "Adicional Tempo Serviço", "Adicional por tempo de serviço", "Adicional em virtude do tempo de serviço (anuênio, quinquênio, etc.)", "INCOME"),
    (1207, "Comissão", "Comissões, porcentagens, produção", "Valor correspondente a contraprestação de serviço, normalmente baseada em um percentual sobre as vendas totais desse trabalhador", "INCOME"),
    (1210, "Gratificão Convenção Coletiva", "Gratificação por acordo ou convenção coletiva", "Verba estabelecida em acordo ou convenção coletiva de trabalho", "INCOME"),
    (1211, "Gratificão", "Gratificação", "Verba não estabelecida em acordo ou convenção coletiva, mas paga para o empregado em decorrência de ajuste entre as partes ou por liberalidade do empregador, como por exemplo produtividade, assiduidade, etc.", "INCOME"),
    (1214, "Adicional Penosidade", "Adicional de penosidade", "Adicional pela realização de atividade árdua que exija do trabalhador esforço, atenção ou vigilância acima do comum", "INCOME"),
    (1299, "Outros adicionais", "Outros adicionais", "Valores relativos a outros adicionais não previstos nos demais itens", "INCOME"),
    (1300, "PRL", "PLR - Participação em Lucros ou Resultados", "Valor correspondente a participação em lucros ou resultados da empresa, de acordo com lei específica", "INCOME"),
    (1350, "Bolsa Estudo - Estagiário", "Bolsa de estudo - Estagiário", "Valor devido ao estagiário em atividades práticas de complementação do currículo escolar, inclusive os valores pagos a título de recesso remunerado - Lei 11.788/2008", "INCOME"),
    (1401, "Abono", "Abono", "Qualquer abono concedido de forma espontânea ou em virtude de acordo ou convenção coletiva, norma, etc.", "INCOME"),
    (1402, "Abono PIS/PASEP", "Abono PIS/PASEP", "Abono e/ou rendimento do PIS/PASEP repassado pelo empregador ou órgão público", "INCOME"),
    (1403, "Abono Legal", "Abono legal", "As importâncias recebidas a título de ganhos eventuais e os abonos expressamente desvinculados do salário, por força da lei", "INCOME"),
    (1404, "Auxílio Babá", "Auxílio babá", "Valor relativo a reembolso de despesas com babá, limitado ao menor salário de contribuição mensal e condicionado à comprovação do registro na carteira de trabalho e previdência social da empregada, do pagamento da remuneração e do recolhimento da contribuição previdenciária, pago em conformidade com a legislação trabalhista, observado o limite máximo de 6 (seis) anos de idade da criança (caso haja previsão em acordo coletivo da categoria, este limite de idade poderá ser maior)", "INCOME"),
    (1405, "Assistência Médica", "Assistência médica", "Valor pago diretamente ao trabalhador a título de assistência médica ou odontológica, inclusive o reembolso de despesas com medicamentos, óculos, aparelhos ortopédicos, despesas médico-hospitalares e outras similares", "INCOME"),
    (1406, "Auxílio Creche", "Auxílio-creche", "O reembolso creche pago em conformidade com a legislação trabalhista, observado o limite máximo de 6 (seis) anos de idade da criança, quando devidamente comprovadas as despesas realizadas. Caso haja previsão em acordo coletivo da categoria, este limite de idade poderá ser maior", "INCOME"),
    (1407, "Auxílio Educação", "Auxílio-educação", "Valor relativo a plano educacional, ou bolsa de estudo, que vise à educação básica de trabalhadores e seus dependentes e, desde que vinculada às atividades desenvolvidas pela empresa, à educação profissional e tecnológica de trabalhadores, nos termos da Lei 9.394/1996", "INCOME"),
    (1409, "Salário Família", "Salário-família", "	Valor do salário-família, conforme limite legal, em virtude do número de filhos menores de 14 anos, ou inválidos de qualquer idade", "INCOME"),
    (1410, "Auxílio Local Difícil Acesso", "Auxílio - Locais de difícil acesso", "Valor correspondente a transporte, habitação e alimentação fornecido ao trabalhador contratado para prestar serviço em localidade distante da sua residência, em canteiro de obras ou local que, por força da atividade, exija deslocamento e estada", "INCOME"),
    (1411, "Auxílio Natalidade", "Auxílio-natalidade", "Valor relativo ao nascimento do filho de servidor público, previsto em lei", "INCOME"),
    (1412, "Abono Permanência", "Abono permanência", "Valor relativo ao abono de permanência, de acordo com a CF/1988", "INCOME"),
    (1602, "Ajuda Custo Transferência", "Ajuda de custo de transferência", "Ajuda de custo em parcela única, em razão de transferência de local de trabalho", "INCOME"),
    (1603, "Ajuda Custo", "Ajuda de custo", "Ajuda de custo paga ao trabalhador", "INCOME"),
    (1604, "Ajuda Custo 50%", "Ajuda de custo - Acima de 50% da remuneração mensal", "Ajuda de custo paga ao trabalhador, superior a 50% da sua remuneração mensal", "INCOME"),
    (1619, "Ajuda Compensatória", "Ajuda compensatória - Programa Emergencial de Manutenção do Emprego e da Renda", "Ajuda compensatória paga pelo empregador ao empregado durante período de suspensão do contrato de trabalho ou redução proporcional de salário e jornada", "INCOME"),
    (1620, "Ressarcimento Uso Veículo Próprio", "Ressarcimento de despesas pelo uso de veículo próprio", "Ressarcimento de despesas ao trabalhador, pela utilização de veículo de sua propriedade", "INCOME"),
    (1621, "Ressarcimento Despesas Viagem", "Ressarcimento de despesas de viagem, exceto despesas com veículos", "Ressarcimento de despesas pagas com recursos do trabalhador em viagens a trabalho", "INCOME"),
    (1623, "Ressarcimento Provisão", "Ressarcimento de provisão", "Ressarcimento de desconto efetuado em recibos de férias relativo a provisão de contribuição previdenciária", "INCOME"),
    (1629, "Ressarcimento Outras Despesas", "Ressarcimento de outras despesas", "Ressarcimento de outras despesas pagas pelo trabalhador, não previstas nos demais itens", "INCOME"),
    (1650, "Diárias Viagem", "Diárias de viagem", "Diárias de viagem ao trabalhador", "INCOME"),
    (1651, "Diárias Viagem Até 50%", "Diárias de viagem - Até 50% do salário", "Diárias de viagem ao trabalhador, desde que não exceda a 50% do seu salário-base mensal", "INCOME"),
    (1652, "Diárias Viagem Acima 50%", "Diárias de viagem - Acima de 50% do salário", "Diárias de viagem superior a 50% do salário-base mensal", "INCOME"),
    (1801, "Alimentação", "Alimentação", "Auxílio-alimentação", "INCOME"),
    (1805, "Moradia", "Moradia", "Auxílio-moradia", "INCOME"),
    (1806, "Alimentação Com PAT", "Alimentação em ticket ou cartão, vinculada ao PAT", "Alimentação concedida sob a forma de ticket ou cartão, por empresa vinculada ao Programa de Alimentação do Trabalhador - PAT", "INCOME"),
    (1807, "Alimentação Sem PAT", "Alimentação em ticket ou cartão, não vinculada ao PAT", "Alimentação concedida sob a forma de ticket ou cartão, por empresa não vinculada ao PAT", "INCOME"),
    (1808, "Cesta Básica Com PAT", "Cesta básica ou refeição, vinculada ao PAT", "Alimentação concedida sob a forma de cesta básica ou refeição, por empresa vinculada ao PAT", "INCOME"),
    (1809, "Cesta Básica Sem PAT", "Cesta básica ou refeição, não vinculada ao PAT", "Alimentação concedida sob a forma de cesta básica ou refeição, por empresa não vinculada ao PAT", "INCOME"),
    (1810, "Transporte", "Transporte", "Auxílio-transporte ou vale-transporte", "INCOME"),
    (1899, "Outros Auxílios", "Outros auxílios", "Outros auxílios", "INCOME"),
    (1901, "Juros ou Atualização Monetária", "Juros e/ou atualização monetária", "Juros e/ou atualização monetária devidos pelo atraso no pagamento de valores por exercício de emprego, cargo ou função", "INCOME"),
    (2501, "Prêmios", "Prêmios", "Liberalidades concedidas pelo empregador em forma de bens, serviços ou valor em dinheiro a empregado ou a grupo de empregados, em razão de desempenho superior ao ordinariamente esperado no exercício de suas atividades", "INCOME"),
    (2502, "Liberdades Em Duas Parcelas Anuais", "Liberalidades concedidas em mais de duas parcelas anuais", "Liberalidades concedidas pelo empregador em forma de bens, serviços ou valor em dinheiro a empregado ou a grupo de empregados, em razão de desempenho superior ao ordinariamente esperado no exercício de suas atividades, em mais de duas parcelas anuais", "INCOME"),
    (2801, "Quarentena Remunerada", "Quarentena remunerada", "Valor equivalente a remuneração se em exercício estivesse, devida ao trabalhador desligado, em período de quarentena", "INCOME"),
    (2901, "Empréstimos", "Empréstimos", "Empréstimos ao trabalhador para posterior desconto", "INCOME"),
    (2902, "Vestuário e Equipamentos", "Vestuário e equipamentos", "Valor correspondente a vestuários, equipamentos e outros acessórios fornecidos ao trabalhador e utilizados no local de trabalho para prestação dos respectivos serviços", "INCOME"),
    (2903, "Vestuário e Equipamentos", "Vestuário e equipamentos", "Valor correspondente a vestuários, equipamentos e outros acessórios quando esses se constituírem em salário utilidade", "INCOME"),
    (2920, "Reembolsos Diversos", "Reembolsos diversos", "Valor relativo a reembolsos diversos referentes a descontos indevidos efetuados em competências anteriores", "INCOME"),
    (2930, "Insuficiência Saldo", "Insuficiência de saldo", "Valor lançado em folha de pagamento para cobertura de excesso de descontos em relação a vencimentos, tanto o valor do vencimento no mês em que houver a insuficiência de saldo, como o respectivo desconto no(s) mês(es) posteriores", "INCOME"),
    (3501, "Remuneração Prestação Serviço", "Remuneração por prestação de serviços", "Remuneração (inclusive adiantamentos) a contribuintes individuais, inclusive honorários, em trabalhos de natureza eventual e sem vínculo trabalhista", "INCOME"),
    (3505, "Pró-Labore Empregados", "Retiradas (pró-labore) de diretores empregados", "Pró-labore ou retirada (remuneração) a diretores empregados (CLT)", "INCOME"),
    (3506, "Pró-Labore Diretores Não Empregados", "Retiradas (pró-labore) de diretores não empregados", "Pró-labore ou retirada (remuneração) a diretores não empregados", "INCOME"),
    (3508, "Pró-Labore Sócios", "Retiradas (pró-labore) de proprietários ou sócios", "Pró-labore ou retirada (remuneração) a proprietários ou sócios da empresa", "INCOME"),
    (3509, "Honorários Conselheiros", "Honorários a conselheiros", "Valor correspondente a honorários pagos a membros de conselho", "INCOME"),
    (4010, "Auxílio Doença", "Complementação salarial de auxílio-doença", "Complementação salarial de auxílio-doença ao trabalhador afastado por acidente de trabalho ou por doença", "INCOME"),
    (4050, "Salário Maternidade", "Salário-maternidade", "Remuneração mensal da trabalhadora empregada durante a licença maternidade, quando paga pelo contratante ou órgão público", "INCOME"),
    (4051, "Salário Maternidade - 13º Salário", "Salário-maternidade - 13° salário", "Valor correspondente ao 13° salário pago pelo contratante ou órgão público, no período de licença maternidade", "INCOME"),
    (5001, "13º Salário", "13° salário", "Valor relativo ao 13° salário de trabalhador, inclusive as médias de 13° salário (horas extras, adicional noturno, etc.), exceto se relativo à primeira parcela ou se pago em rescisão contratual – nessa opção deve ser classificado também o valor pago mensalmente ao trabalhador avulso e ao empregado com contrato de trabalho intermitente, a título de 13° salário", "INCOME"),
    (5005, "13º Salário Complementar", "13° salário complementar", "Valor do 13° salário complementar relativo a diferenças apuradas não consideradas na folha de fechamento do 13° salário", "INCOME"),
    (5501, "Adiantamento Salário", "Adiantamento de salário", "Valor relativo a adiantamento, antecipação ou pagamento parcial de folha de salários", "INCOME"),
    (5504, "Adiantamento 13º Salário", "13º salário - Adiantamento", "Valor relativo a adiantamento do 13° salário", "INCOME"),
    (5510, "Adiantamento Benefícios Previdenciários", "Adiantamento de benefícios previdenciários", "Valor relativo a adiantamento de benefícios a serem pagos pela Previdência Social Oficial", "INCOME"),

    -- Descontos: Códigos 9000 à 9999
    (9200, "Desconto Adiantamentos", "Desconto de adiantamentos", "Valor relativo a descontos a título de adiantamentos em geral, como de salários e outros, exceto a 1ª parcela do 13° salário", "DEDUCTION"),
    (9201, "INSS", "Contribuição previdenciária", "Desconto a título de contribuição previdenciária", "DEDUCTION"),
    (9203, "IRRF", "Imposto de Renda Retido na Fonte", "Desconto a título de Imposto de Renda Retido na Fonte - IRRF", "DEDUCTION"),
    (9205, "Provisão Contribuição Previdenciária", "Provisão de contribuição previdenciária", "Desconto efetuado em recibos de férias relativo a provisão de contribuição previdenciária", "DEDUCTION"),
    (9207, "Faltas", "Faltas", "Desconto decorrente de ausência de trabalho durante todo o dia em razão de, por exemplo, falta injustificada, suspensão disciplinar, greve", "DEDUCTION"),
    (9208, "Atrasos", "Atrasos", "Desconto decorrente de ausência de trabalho em razão de, por exemplo, atrasos no início da jornada de trabalho ou de saída antecipada do trabalhador", "DEDUCTION"),
    (9209, "Faltas ou Atrasos", "Faltas ou atrasos", "Desconto correspondente a faltas, atrasos no início da jornada de trabalho ou à saída antecipada do trabalhador", "DEDUCTION"),
    (9210, "DSRs, Faltas e Atrasos", "DSRs faltas e atrasos", "Desconto correspondente ao Descanso Semanal Remunerado - DSR, calculado sobre faltas e atrasos do trabalhador", "DEDUCTION"),
    (9211, "DSRs Faltas", "DSRs sobre faltas", "Desconto correspondente ao Descanso Semanal Remunerado - DSR, calculado sobre faltas do trabalhador", "DEDUCTION"),
    (9212, "DSRs Atrasos", "DSRs sobre atrasos", "Desconto correspondente ao Descanso Semanal Remunerado - DSR, calculado sobre atrasos do trabalhador", "DEDUCTION"),
    (9213, "Pensão Alimentícia", "Pensão alimentícia", "Desconto correspondente a pensão alimentícia sobre o salário mensal, 13° salário, PLR e férias", "DEDUCTION"),
    (9214, "13° Salário - Desconto Adiantamento", "13° salário - Desconto de adiantamento", "Desconto de antecipação do 13° salário", "DEDUCTION"),
    (9216, "Desconto Vale Transporte", "Desconto de vale-transporte", "Desconto do vale-transporte referente a participação do trabalhador no custo ou em virtude de concessão do benefício em valor maior", "DEDUCTION"),
    (9217, "Contribuição Outras Entidades e Fundos", "Contribuição a Outras Entidades e Fundos", "Desconto relativo a contribuições destinadas a outras entidades e fundos (Terceiros), como por exemplo, Sest, Senat, etc., devidas por algumas categorias de contribuintes individuais", "DEDUCTION"),
    (9218, "Retenções judiciais", "Retenções judiciais", "Desconto relativo a retenções de verbas devidas a trabalhadores por ordem judicial, exceto pensão alimentícia", "DEDUCTION"),
    (9219, "Desconto Assistência Médica ou Odontológica", "Desconto de assistência médica ou odontológica", "Desconto referente a participação do trabalhador no custo de assistência médica ou odontológica, ou em virtude de concessão do benefício em valor maior", "DEDUCTION"),
    (9220, "Alimentação - Desconto", "Alimentação - Desconto", "Desconto referente a participação do trabalhador no custo ou em virtude de concessão do benefício em valor maior", "DEDUCTION"),
    (9221, "Desconto Férias", "Desconto de férias", "Valor correspondente a remuneração (dias) de férias do mês corrente pago no mês anterior ou adiantamento de férias", "DEDUCTION"),
    (9222, "Desconto Outros Impostos e Contribuições", "Desconto de outros impostos e contribuições", "Desconto de outros impostos, taxas e contribuições, exceto Imposto de Renda Retido na Fonte, contribuição previdenciária e contribuições destinadas a outras entidades e fundos (Terceiros)", "DEDUCTION"),
    (9226, "Desconto de Férias - Abono", "Desconto de férias - Abono", "Desconto correspondente ao abono de férias pago no mês anterior ou adiantamento de férias", "DEDUCTION"),
    (9230, "Contribuição Sindical", "Contribuição sindical laboral", "Valor correspondente ao desconto da contribuição laboral correspondente a um dia de trabalho a título de contribuição sindical", "DEDUCTION"),
    (9231, "Mensalidade Sindical ou Associativa", "Mensalidade sindical ou associativa", "Valor correspondente ao desconto referente a mensalidade sindical ou associativa do trabalhador", "DEDUCTION"),
    (9232, "Contribuição Sindical - Assistencial", "Contribuição sindical - Assistencial", "Valor correspondente ao desconto da contribuição destinada ao custeio das atividades assistenciais do sindicato", "DEDUCTION"),
    (9233, "Contribuição Sindical - Confederativa", "Contribuição sindical - Confederativa", "Valor correspondente ao desconto da contribuição destinada ao custeio do sistema confederativo", "DEDUCTION"),
    (9240, "Desconto Alimentação Pecúnia", "Alimentação concedida em pecúnia - Desconto", "Desconto referente à alimentação concedida sob a forma de pecúnia", "DEDUCTION"),
    (9241, "Desconto Alimentação com PAT", "Alimentação em ticket ou cartão, vinculada ao PAT - Desconto", "Desconto referente à participação do trabalhador no custo de alimentação concedida sob a forma de ticket ou cartão, por empresa vinculada ao Programa de Alimentação do Trabalhador - PAT", "DEDUCTION"),
    (9242, "Desconto Alimentação sem PAT", "Alimentação em ticket ou cartão, não vinculada ao PAT - Desconto", "Desconto referente à participação do trabalhador no custo de alimentação concedida sob a forma de ticket ou cartão, por empresa não vinculada ao PAT", "DEDUCTION"),
    (9243, "Desconto Cesta Básica com PAT", "Cesta básica ou refeição, vinculada ao PAT - Desconto", "Desconto referente à participação do trabalhador no custo de alimentação concedida sob a forma de cesta básica ou refeição, por empresa vinculada ao PAT", "DEDUCTION"),
    (9244, "Desconto Cesta Básica sem PAT", "Cesta básica ou refeição, não vinculada ao PAT - Desconto", "Desconto referente à participação do trabalhador no custo de alimentação concedida sob a forma de cesta básica ou refeição, por empresa não vinculada ao PAT", "DEDUCTION"),
    (9250, "Desconto Seguro Vida", "Seguro de vida - Desconto", "Desconto referente a participação do trabalhador no custo ou em virtude de concessão do benefício em valor maior", "DEDUCTION"),
    (9255, "Desconto Empréstimo", "Empréstimos do empregador - Desconto", "Desconto de trabalhadores a título de empréstimos efetuados pelo empregador ao trabalhador", "DEDUCTION"),
    (9258, "Desconto Convênios", "Convênios", "Desconto relativos a convênios diversos com empresas para fornecimento de produtos ou serviços ao empregado, sem pagamento imediato, mas com posterior desconto em folha de pagamento como farmácias, supermercados, etc.", "DEDUCTION"),
    (9270, "Desconto Danos e Prejuízos", "Danos e prejuízos causados pelo trabalhador", "Desconto do trabalhador para reparar danos e prejuízos por ele causados", "DEDUCTION"),
    (9290, "Desconto Pagamento Indevido Meses Anteriores", "Desconto de pagamento indevido em meses anteriores", "Valor correspondente a desconto de verbas pagas indevidamente ao trabalhador em meses anteriores e que estão sendo descontadas no mês de referência, exceto valores relativos a assistência médica, alimentação, previdência complementar e seguro de vida", "DEDUCTION"),
    (9293, "Honorários Advocatícios", "Honorários advocatícios", "Valor descontado do trabalhador por determinação judicial a ser pago ao advogado/escritório de advocacia", "DEDUCTION"),
    (9299, "Outros descontos", "Outros descontos", "Outros descontos não previstos nos demais itens", "DEDUCTION"),

    -- Neutros: Códigos 9900
    (9901, "Base Cálculo Contribuição Previdenciária", "Base de cálculo da contribuição previdenciária", "Valor total da base de cálculo da contribuição previdenciária", "NEUTRAL"),
    (9902, "Base Cálculo FGTS", "Total da base de cálculo do FGTS", "Valor total da base de cálculo do FGTS", "NEUTRAL"),
    (9903, "Base Cálculo IRRF", "Total da base de cálculo do IRRF", "Valor total da base de cálculo do Imposto de Renda Retido na Fonte", "NEUTRAL"),
    (9908, "FGTS - Depósito", "FGTS - Depósito", "Valor do depósito do FGTS", "NEUTRAL"),
    (9910, "Seguros", "Seguros", "Valor relativo a prêmio de seguro de vida em grupo pago a empresa de seguros como benefício do trabalhador", "NEUTRAL"),
    (9911, "Assistência Médica", "Assistência Médica", "Valor não relativo a vencimento ou desconto, relativo à assistência prestada por serviço médico ou odontológico, próprio da empresa ou por ela conveniado, como benefício ao trabalhador", "NEUTRAL"),
    (9930, "Salário Maternidade Previdência Social", "Salário-maternidade pago pela Previdência Social", "Valor correspondente à remuneração mensal do(a) trabalhador(a) durante a licença maternidade, quando paga pela Previdência Social (RGPS ou pela Unidade Gestora do RPPS)", "NEUTRAL"),
    (9931, "Salário Maternidade Previdência Social - 13º Salário", "Salário-maternidade pago pela Previdência Social - 13° salário", "Valor correspondente ao 13° salário do(a) trabalhador(a) durante a licença maternidade, quando pago pela Previdência Social (RGPS ou pela Unidade Gestora do RPPS)", "NEUTRAL"),
    (9932, "Auxílio Doença Acidentário", "Auxílio-doença acidentário", "Valor relativo a base de cálculo do FGTS referente a afastamento decorrente de acidente de trabalho", "NEUTRAL"),
    (9933, "Auxílio Doença", "Auxílio-doença", "Valor de benefício previdenciário pago por Regime Próprio de Previdência Social ou valor de auxílio-doença dedutível conforme Lei 13.982/2020 (Covid-19)", "NEUTRAL"),
    (9938, "Isenção IRRF - 65 anos", "Isenção IRRF - 65 anos", "Valor da parcela isenta dos rendimentos de aposentadoria e pensão, transferência para a reserva remunerada ou reforma, pagos por órgão público de previdência oficial ou por entidade de previdência complementar, no caso de contribuinte com idade igual ou superior a 65 anos", "NEUTRAL"),
    (9939, "Outros Valores Tributáveis", "Outros valores tributáveis", "Valor não relativo a vencimento ou desconto mas considerado como base de cálculo do FGTS, e/ou da contribuição previdenciária e/ou do Imposto de Renda Retido na Fonte inclusive suas deduções e isenções", "NEUTRAL"),
    (9950, "Horas Extraordinárias - Banco de Horas", "Horas extraordinárias - Banco de horas", "Quantidade (em número decimal com dois dígitos) de horas extraordinárias incorporadas ao banco de horas", "NEUTRAL"),
    (9951, "Horas Compensadas - Banco de Horas", "Horas compensadas - Banco de horas", "Quantidade (em número decimal com dois dígitos) de horas compensadas no banco de horas", "NEUTRAL"),
    (9989, "Outros valores Informativos", "Outros Valores Informativos", "Outros valores informativos, que não sejam vencimentos nem descontos", "NEUTRAL");