CREATE TABLE IF NOT EXISTS employee (
    id_employee INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(120) NOT NULL,
    rg VARCHAR(11) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    birth_date DATE NOT NULL,
    gender ENUM('MALE', 'FEMALE', 'OTHER'),
    address_street VARCHAR(100) NOT NULL,
    address_number VARCHAR(6) NOT NULL,
    address_neighborhood VARCHAR(100) NOT NULL,
    address_complement VARCHAR(100),
    address_city VARCHAR(100) NOT NULL,
    address_uf ENUM('AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO') NOT NULL,
    address_zip_code VARCHAR(8) NOT NULL,
    phone VARCHAR(11),
    email VARCHAR(80),
    admission_date DATE NOT NULL,
    time_service_allowance BOOLEAN NOT NULL DEFAULT FALSE,
    department_id INT NOT NULL,
    job_id INT NOT NULL,
    work_shift_id INT NOT NULL,
    salary DECIMAL(10, 2) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id_employee),
    FOREIGN KEY (department_id) REFERENCES department(id_department),
    FOREIGN KEY (job_id) REFERENCES job(id_job),
    FOREIGN KEY (work_shift_id) REFERENCES work_shift(id_work_shift)
);